version: '2'
services:
  stargate:
    image: stargateio/stargate-3_11:v1.0.63
    ports:
      #CQL
      - 9042:9042
      #graphQL
      - 8080:8080
      #Auth
      - 8081:8081
      #REST
      - 8082:8082
      #Metrics
      - 8084:8084
      #gRPC
      - 8090:8090
    mem_limit: 2G
    environment:
      - DATACENTER_NAME=datacenter1
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargate
      - CLUSTER_VERSION=3.11
      - DEVELOPER_MODE=true