server:
  port: 9292
  
spring:
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

management:
  server:
    port: 9001
    address: 127.0.0.1
  metrics:
    export:
       prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        
astra:
  application-token: AstraCS:RjwrkBwzbcZZDyFZAvuhmCRJ:71cea89b9d3ea45a1c15675ab38f6cd861633bfc521467f525d2f57ced0e6b14
  database-id: d7d49808-9f08-403b-84e5-19ae47d1da69
  database-region: eu-central-1
  keyspace: quickstart
  metrics:
    enabled: true