server:
  port: 9292
  
spring:
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS

management:
  server:
    port: 9001
    address: 127.0.0.1
  metrics:
    export:
       prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        
astra:
  application-token: AstraCS:gdZaqzmFZszaBTOlLgeecuPs:edd25600df1c01506f5388340f138f277cece2c93cb70f4b5fa386490daa5d44
  database-id: f0b7a8cf-1f2f-4415-99d0-334760666ca3
  database-region: eu-west-1
  keyspace: quickstart
  #metrics:
  #  enabled: true