version: '2'

services:
  
  dc2n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9062:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC2
  
  dc2n2: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc2n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC2
  
  dc2n3: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc2n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC2
   
networks:
  backend:
