version: '2'

services:
  
  dc1n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9052:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC1
  
  dc1n2: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc1n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC1
  
  dc1n3: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc1n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC1
  
  dc2n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9062:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC2
  dc2n2: 
    image: cassandra:3.11.11
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC2
  dc2n3: 
    image: cassandra:3.11.11
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - backend-2
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - DATACENTER=DC2
         
      
      
  stargate:
    image: stargateio/stargate-3_11:v1.0.38
    depends_on: 
      - backend-1
    networks:
      - backend
    ports:
      - 9045:9042
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8084:8084
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=c3-demo-cluster
      - CLUSTER_VERSION=3.11
      - SEED=backend-1
      - RACK_NAME=rack1
      - DATACENTER_NAME=DC1
      - ENABLE_AUTH=true
  stargate-2:
    image: stargateio/stargate-3_11:v1.0.38
    depends_on: 
      - backend-1
    networks:
      - backend
    ports:
      - 9046:9042
      - 9090:8080
      - 9091:8081
      - 9092:8082
      - 9094:8084
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=c3-demo-cluster
      - CLUSTER_VERSION=3.11
      - SEED=backend-1
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true      
networks:
  backend:
