version: '2'

services:
  
  dc1n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9052:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc1n2: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc1n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc1n3: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc1n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      
      
  dc2n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9062:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1,dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc2n2:
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc2n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1,dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc2n3: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc2n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1,dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
   
networks:
  backend:
