name: SDK Tests
on:
  pull_request:
    branches:
      - master
jobs:
  sdk-tests:
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
      ASTRA_DB_KEYSPACE: ${{ secrets.ASTRA_DB_KEYSPACE }}
      ASTRA_DB_ID: ${{ secrets.ASTRA_DB_ID }}
      ASTRA_DB_REGION: ${{ secrets.ASTRA_DB_REGION }}
      STARGATE_USERNAME: ${{ secrets.STARGATE_USERNAME }}
      STARGATE_PASSWORD: ${{ secrets.STARGATE_PASSWORD }}
      STARGATE_LOCAL_DC: datacenter1
      STARGATE_ENDPOINT_CQL: "127.0.0.1"
      STARGATE_ENDPOINT_DOC: http://127.0.0.1:8082
      STARGATE_ENDPOINT_REST: http://127.0.0.1:8082
      STARGATE_ENDPOINT_AUTH: http://127.0.0.1:8082
    runs-on: ubuntu-latest
    services:
      stargate:
        image: stargateio/stargate-dse-68:v1.0.32
        env:
          CLUSTER_NAME: stargate
          CLUSTER_VERSION: 6.8
          DEVELOPER_MODE: true
          DSE: 1
        ports:
          - 8080:8080
          - 8081:8081
          - 8082:8082
          - 9042:9042
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Test with Maven
        run: mvn test
        